"""Auto-generated by tt. Do not edit by hand."""
from __future__ import annotations

from datetime import date
from app.implementation._support.bigjs import Big
from app.implementation._support.datefns import _date_format
from app.implementation._support.ghostfolio_helper import _DATE_FORMAT
from app.implementation._support.nest_logger import Logger

class PortfolioCalculator:
    def calculate_overall_performance(self, positions):
        pass


    def get_performance_calculation_type(self):
        pass


    def get_data_provider_infos(self):
        return self.data_provider_infos


    async def get_dividend_in_base_currency(self):
        (awaitself.snapshot_promise)
        return get_sum(self.snapshot.positions.map((lambda _arg: dividend_in_base_currency)))


    async def get_fees_in_base_currency(self):
        (awaitself.snapshot_promise)
        return self.snapshot.total_fees_with_currency_effect


    async def get_interest_in_base_currency(self):
        (awaitself.snapshot_promise)
        return self.snapshot.total_interest_with_currency_effect


    def get_investments(self):
        if (self.transaction_points.length == 0):
            return []
        return self.transaction_points.map((lambda transaction_point: {'date': transaction_point.date, 'investment': transaction_point.items.reduce((lambda investment, transaction_point_symbol: investment.plus(transaction_point_symbol.investment)), Big(0))}))


    def get_investments_by_group(self, _arg0):
        data = _arg0['data']
        group_by = _arg0['group_by']
        grouped_data = {}
        for date, investment_value_with_currency_effect in data:
            date_group = (date.substring(0, 7) if (group_by == 'month') else date.substring(0, 4))
            grouped_data[date_group] = ((grouped_data[date_group] or Big(0)) + investment_value_with_currency_effect)
        return object.keys(grouped_data).map((lambda date_group: {'date': (f'{date_group}-01' if (group_by == 'month') else f'{date_group}-01-01'), 'investment': grouped_data[date_group].to_number()}))


    async def get_liabilities_in_base_currency(self):
        (awaitself.snapshot_promise)
        return self.snapshot.total_liabilities_with_currency_effect


    async def get_performance(self, _arg0):
        end = _arg0['end']
        start = _arg0['start']
        (awaitself.snapshot_promise)
        _destr = self.snapshot
historical_data = _destr['historical_data']
        chart = []
        net_performance_at_start_date = None
        net_performance_with_currency_effect_at_start_date = None
        total_investment_values_with_currency_effect = []
        for historical_data_item in historical_data:
            date = reset_hours(parse_date(historical_data_item.date))
            if ((not is_before(date, start)) and (not is_after(date, end))):
                if (not is_number(net_performance_at_start_date)):
                    net_performance_at_start_date = historical_data_item.net_performance
                    net_performance_with_currency_effect_at_start_date = historical_data_item.net_performance_with_currency_effect
                net_performance_since_start_date = (historical_data_item.net_performance - net_performance_at_start_date)
                net_performance_with_currency_effect_since_start_date = (historical_data_item.net_performance_with_currency_effect - net_performance_with_currency_effect_at_start_date)
                if (historical_data_item.total_investment_value_with_currency_effect > 0):
                    total_investment_values_with_currency_effect.push(historical_data_item.total_investment_value_with_currency_effect)
                time_weighted_investment_value = ((sum(total_investment_values_with_currency_effect) / total_investment_values_with_currency_effect.length) if (total_investment_values_with_currency_effect.length > 0) else 0)
                chart.push({**historical_data_item, 'netPerformance': (historical_data_item.net_performance - net_performance_at_start_date), 'netPerformanceWithCurrencyEffect': net_performance_with_currency_effect_since_start_date, 'netPerformanceInPercentage': (0 if (time_weighted_investment_value == 0) else (net_performance_since_start_date / time_weighted_investment_value)), 'netPerformanceInPercentageWithCurrencyEffect': (0 if (time_weighted_investment_value == 0) else (net_performance_with_currency_effect_since_start_date / time_weighted_investment_value))})
        return {'chart': chart}


    async def get_snapshot(self):
        (awaitself.snapshot_promise)
        return self.snapshot


    def get_start_date(self):
        first_account_balance_date = None
        first_activity_date = None
        try:
            first_account_balance_date_string = self.account_balance_items[0].date
            first_account_balance_date = (parse_date(first_account_balance_date_string) if first_account_balance_date_string else date())
        except Exception as error:
            first_account_balance_date = date()
        try:
            first_activity_date_string = self.transaction_points[0].date
            first_activity_date = (parse_date(first_activity_date_string) if first_activity_date_string else date())
        except Exception as error:
            first_activity_date = date()
        return min([first_account_balance_date, first_activity_date])


    def get_symbol_metrics(self, _arg0):
        chart_date_map = _arg0['chart_date_map']
        data_source = _arg0['data_source']
        end = _arg0['end']
        exchange_rates = _arg0['exchange_rates']
        market_symbol_map = _arg0['market_symbol_map']
        start = _arg0['start']
        symbol = _arg0['symbol']
        pass


    def get_transaction_points(self):
        return self.transaction_points


    def compute_transaction_points(self):
        self.transaction_points = []
        symbols = {}
        last_date = None
        last_transaction_point = None
        for date, fee, fee_in_base_currency, quantity, symbol_profile, tags, type, unit_price in self.activities:
            current_transaction_point_item = None
            asset_sub_class = symbol_profile.asset_sub_class
            currency = symbol_profile.currency
            data_source = symbol_profile.data_source
            factor = get_factor(type)
            skip_errors = (not (not symbol_profile.user_id))
            symbol = symbol_profile.symbol
            old_accumulated_symbol = symbols[symbol]
            if old_accumulated_symbol:
                investment = old_accumulated_symbol.investment
                new_quantity = ((quantity * factor) + old_accumulated_symbol.quantity)
                if (type == 'BUY'):
                    if (old_accumulated_symbol.investment >= 0):
                        investment = (old_accumulated_symbol.investment + (quantity * unit_price))
                    else:
                        investment = (old_accumulated_symbol.investment + (quantity * old_accumulated_symbol.average_price))
                elif (type == 'SELL'):
                    if (old_accumulated_symbol.investment > 0):
                        investment = (old_accumulated_symbol.investment - (quantity * old_accumulated_symbol.average_price))
                    else:
                        investment = (old_accumulated_symbol.investment - (quantity * unit_price))
                if (abs(new_quantity) < number.EPSILON):
                    investment = Big(0)
                    new_quantity = Big(0)
                current_transaction_point_item = {'assetSubClass': asset_sub_class, 'currency': currency, 'dataSource': data_source, 'investment': investment, 'skipErrors': skip_errors, 'symbol': symbol, 'activitiesCount': (old_accumulated_symbol.activities_count + 1), 'averagePrice': (Big(0) if new_quantity.eq(0) else investment.div(new_quantity).abs()), 'dateOfFirstActivity': old_accumulated_symbol.date_of_first_activity, 'dividend': Big(0), 'fee': old_accumulated_symbol.fee.plus(fee), 'feeInBaseCurrency': old_accumulated_symbol.fee_in_base_currency.plus(fee_in_base_currency), 'includeInHoldings': old_accumulated_symbol.include_in_holdings, 'quantity': new_quantity, 'tags': old_accumulated_symbol.tags.concat(tags)}
            else:
                current_transaction_point_item = {'assetSubClass': asset_sub_class, 'currency': currency, 'dataSource': data_source, 'fee': fee, 'feeInBaseCurrency': fee_in_base_currency, 'skipErrors': skip_errors, 'symbol': symbol, 'tags': tags, 'activitiesCount': 1, 'averagePrice': unit_price, 'dateOfFirstActivity': date, 'dividend': Big(0), 'includeInHoldings': INVESTMENT_ACTIVITY_TYPES.includes(type), 'investment': unit_price.mul(quantity).mul(factor), 'quantity': quantity.mul(factor)}
            current_transaction_point_item.tags = uniq_by(current_transaction_point_item.tags, 'id')
            symbols[symbol_profile.symbol] = current_transaction_point_item
            items = (last_transaction_point.items or [])
            new_items = items.filter((lambda _arg: (symbol != symbol_profile.symbol)))
            new_items.push(current_transaction_point_item)
            new_items.sort((lambda a, b: a.symbol.locale_compare(b.symbol)))
            fees = Big(0)
            if (type == 'FEE'):
                fees = fee
            interest = Big(0)
            if (type == 'INTEREST'):
                interest = (quantity * unit_price)
            liabilities = Big(0)
            if (type == 'LIABILITY'):
                liabilities = (quantity * unit_price)
            if ((last_date != date) or (last_transaction_point == None)):
                last_transaction_point = {'date': date, 'fees': fees, 'interest': interest, 'liabilities': liabilities, 'items': new_items}
                self.transaction_points.push(last_transaction_point)
            else:
                last_transaction_point.fees = (last_transaction_point.fees + fees)
                last_transaction_point.interest = (last_transaction_point.interest + interest)
                last_transaction_point.items = new_items
                last_transaction_point.liabilities = (last_transaction_point.liabilities + liabilities)
            last_date = date


    async def initialize(self):
        start_time_total = performance.now()
        cached_portfolio_snapshot = None
        is_cached_portfolio_snapshot_expired = False
        job_id = self.user_id
        try:
            cached_portfolio_snapshot_value = (awaitself.redis_cache_service.get(self.redis_cache_service.get_portfolio_snapshot_key({'filters': self.filters, 'userId': self.user_id})))
            _destr = JSON.parse(cached_portfolio_snapshot_value)
expiration = _destr['expiration']
portfolio_snapshot = _destr['portfolio_snapshot']
            cached_portfolio_snapshot = plain_to_class(portfolio_snapshot, portfolio_snapshot)
            if is_after(date(), date(expiration)):
                is_cached_portfolio_snapshot_expired = True
        except Exception as _exc:
            pass
        if cached_portfolio_snapshot:
            self.snapshot = cached_portfolio_snapshot
            Logger.debug(f'Fetched portfolio snapshot from cache in {((performance.now() - start_time_total) / 1000).to_fixed(3)} seconds', 'PortfolioCalculator')
            if is_cached_portfolio_snapshot_expired:
                self.portfolio_snapshot_service.add_job_to_queue({'data': {'calculationType': self.get_performance_calculation_type(), 'filters': self.filters, 'userCurrency': self.currency, 'userId': self.user_id}, 'name': PORTFOLIO_SNAPSHOT_PROCESS_JOB_NAME, 'opts': {**PORTFOLIO_SNAPSHOT_PROCESS_JOB_OPTIONS, 'jobId': job_id, 'priority': PORTFOLIO_SNAPSHOT_COMPUTATION_QUEUE_PRIORITY_LOW}})
        else:
            (awaitself.portfolio_snapshot_service.add_job_to_queue({'data': {'calculationType': self.get_performance_calculation_type(), 'filters': self.filters, 'userCurrency': self.currency, 'userId': self.user_id}, 'name': PORTFOLIO_SNAPSHOT_PROCESS_JOB_NAME, 'opts': {**PORTFOLIO_SNAPSHOT_PROCESS_JOB_OPTIONS, 'jobId': job_id, 'priority': PORTFOLIO_SNAPSHOT_COMPUTATION_QUEUE_PRIORITY_HIGH}}))
            job = (awaitself.portfolio_snapshot_service.get_job(job_id))
            if job:
                (awaitjob.finished())
            (awaitself.initialize())


